spring:
  application:
    name: systemGame
web:
  upload-path: file:/home/images/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9011/eureka/
server:
  port: 9013
feign:
  hystrix:
    enabled: true
ribbon:
  #请求处理的超时时间
  ReadTimeout: 10000
  #请求连接的超时时间
  ConnectTimeout: 10000
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 3000
