spring:
  application:
    name: systemGame
  #resources:
    #static-locations: classpath:/static/,classpath:/META-INF/resources,file:/Users/yangzhenze/Downloads/
  #mvc:
    #static-path-pattern: /static/**
  boot:
    admin:
      client:
        url: "http://localhost:9019"
web:
  upload-path: file:/Users/yangzhenze/Downloads/images/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9011/eureka/
server:
  port: 8013
feign:
  hystrix:
    enabled: true
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 15000
management:
  endpoints:
    web:
      exposure:
        include: "*"
#feign日志输出
logging:
  level:
    com.system.service.AdminService: debug
    com.system.service.DictionaryService: debug
    com.system.service.PermissionService: debug
    com.system.service.RoleService: debug

