spring:
  application:
    name: system-game
  zipkin:
    base-url: http://localhost:9014
web:
  upload-path: file:/home/images/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9011/eureka/
server:
  port: 9013
feign:
  hystrix:
    enabled: true
ribbon:
  #请求处理的超时时间
  ReadTimeout: 10000
  #请求连接的超时时间
  ConnectTimeout: 10000
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 3000
management:
  endpoints:
    web:
      exposure:
        include: "*"
#feign日志输出
logging:
  level:
    com.system.service.AdminService: debug
    com.system.service.DictionaryService: debug
    com.system.service.PermissionService: debug
    com.system.service.RoleService: debug
